steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/easyocr-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/easyocr-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'easyocr-api',
        '--image', 'gcr.io/$PROJECT_ID/easyocr-api',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
images:
  - 'gcr.io/$PROJECT_ID/easyocr-api'
