services:
  - name: easyocr
    type: web
    runtime: docker
    repo: https://github.com/govisaa/easyocr
    branch: main  # or your actual branch
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
